config/routes.rb
Demo::Application.routes.draw do
  devise_for :users

   root :to => 'boards#index'

   resources :boards do
      resources :posts
   end

   namespace :admin do
      resources :boards do
         resources :posts
      end
   end

end

app/models/board.rb
class Board < ActiveRecord::Base
   has_many :posts
  attr_accessible :name
end

app/models/post.rb
class Post < ActiveRecord::Base
   belongs_to :user
   belongs_to :board, :counter_cache => true
   #default_scope :order => 'created_at DESC'
   scope :recent, :order => 'updated_at DESC'
   has_attached_file :excerpt_image, :styles =>  {:medium => '300x300>', :thumb => '100x100'}
  attr_accessible :content, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  attr_protected :is_admin

  def is_admin?
     is_admin
  end
end

app/controllers/admin/boards_controller.rb
class Admin::BoardsController < ApplicationController
   layout 'admin'
   before_filter :require_is_admin
  def index
     @boards = Board.all
     respond_to do |format|
        format.html
        format.xml {render :xml => @boards}
     end
  end

  def new
     @board = Board.new
     respond_to do |format|
        format.html
        format.xml {render :xml => @board}
     end
  end

  def edit
     @board = Board.find(params[:id])
  end

  def create
     @board = Board.new(params[:board])
     respond_to do |format|
        if @board.save
           format.html {redirect_to(board_path(@board), :notice => 'Board was successfully created.')}
           format.xml {render :xml => @board, :status => :created, :location => @board}
        else
           format.html {render :action => 'new'}
           format.xml {render :xml => @board.errors, :status => :unprocessable_entity}
        end
     end
  end

  def update
     @board = Board.find(params[:id])
     respond_to do |format|
        if @board.update_attributes(params[:board])
           format.html {redirect_to(board_path(@board), :notice => 'Board was swccessfully updates.')}
           format.xml {head :ok}
        else
           format.html {render :action => 'edit'}
           format.xml {render :xml => @board.errors, :status => :unprocessable_entity}
        end
     end
  end

  def destroy
     @board = Board.find(params[:id])
     @board.destroy
     respond_to do |format|
        format.html {redirect_to(admin_boards_url)}
        format.xml {head :ok}
     end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout 'admin'
  before_filter :find_board
  before_filter :authenticate_user!, :except => [:index]

  def edit
     @post = current_user.posts.find(params[:id])
  end

  def create
     @post = @board.posts.build(params[:post])
     @post.user_id = current_user.id
     if @post.save
        redirect_to board_posts_path(@board)
     end
  end

  def update
     @post = current_user.posts.find(params[:id])
     if @post.update_attributes(params[:post])
        redirect_to board_post_path(@board, @post)
     end
  end

  def destroy
     @post = @board.posts.find(params[:id])
     @post.destroy
     redirect_to board_posts_path(@board)
  end
  protected
  def find_board
     @board = Board.find(params[:board_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def require_is_admin
     unless (current_user && current_user.is_admin?)
        flash[:alert] = 'You must be admin!'
        redirect_to root_path
     end
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
     @boards = Board.all
  end

  def show
     @board = Board.find(params[:id])
     @posts = @board.posts.recent.paginate(:page => params[:page], :per_page => 5)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :find_board
  before_filter :authenticate_user!, :except => [:index, :show]
  def index
     redirect_to board_path(@board)
  end

  def show
     @post = @board.posts.find(params[:id])
  end

  def new
     @post = @board.posts.build
  end

  def edit
     @post = current_user.posts.find(params[:id])
  end

  def create
     @post = @board.posts.build(params[:post])
     @post.user_id = current_user.id
     if @post.save
        redirect_to board_posts_path(@board)
     end
  end

  def update
     @post = current_user.posts.find(params[:id])
     if @post.update_attributes(params[:post])
        redirect_to board_post_path(@board, @post)
     end
  end

  def destroy
     @post = @board.posts.find(params[:id])
     @post.destroy
     redirect_to board_posts_path(@board)
  end
  protected
  def find_board
     @board = Board.find(params[:board_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/boards/_form.html.erb
<% if @board.errors.any? %>
   <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved: </h2>
      <ul>
         <% @board.errors.full_messages.each do |msg| %>
            <li><%- msg %></li>
         <% end %>
      </ul>
   </div>
<% end %>

<div class = "field">
   <%= f.label :name %><br/>
   <%= f.text_field :name %>
</div>
<div class = "actions">
   <%= f.submit %>
</div>

app/views/admin/boards/edit.html.erb
<h1>Edit board</h1>
<%= form_for @board, :url => admin_board_path(@board) do |f| %>
   <%= render :partial => 'form', :locals => {:f => f} %>
<% end %>

<%= link_to 'Show', @board %>
<%= link_to 'Back', admin_boards_path %>

app/views/admin/boards/index.html.erb
<h1>Forum HomePage</h1>
<table>
   <tr>
      <th>ID</th><th>Issue</th><th>management</th>
   </tr>
   <% @boards.each do |board| %>
      <tr>
         <td><%= board.id %></td>
         <td><%= link_to board.name, board_path(board) %></td>
         <td>
            <%= link_to 'Edit', edit_board_path(board) %>
            <%= link_to 'Delete', board_path(board), :confirm => 'Are you sure?', :method => :delete %>
         </td>
      </tr>
   <% end %>
</table>

<%= link_to 'New board', new_board_path %>

app/views/admin/boards/new.html.erb
<h1>New board</h1>
<%= form_for @board, :url => admin_boards_path do |f| %>
   <%= render :partial => 'form', :locals => {:f => f} %>
<% end %>

<%- link_to 'Back', admin_boards_path %>

app/views/admin/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for @post, :url => admin_board_post_path(@board, @post) do |f| %>
   <%= render :partial => 'form', locals => {:f => f} %>
<% end %>
<%= link_to 'Show', board_post_path(@board, @post) %>

app/views/boards/edit.html.erb
<h1>Edit board</h1>
<%= form_for @board, :url => board_path(@board) do |f| %>
   <%= f.label :name, 'Board Name' %>
   <%= f.text_field :name %>
   <%= f.submit 'Update!' %>
<% end %>

app/views/boards/index.html.erb
<h1>Listing boards</h1>

<table>
   <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
   </tr>

   <% @boards.each do |board| %>
      <tr>
         <td><%= board.name %></td>
         <td><%= link_to 'Show', board %></td>
         <% if current_user && current_user.is_admin %>
            <td><%= link_to 'A-Edit', edit_admin_board_path(board) %></td>
            <td><%= link_to 'A-Destroy', admin_boards_path, :confirm => 'Are you sure', :method => :delete %></td>
         <% end %>
      </tr>
   <% end %>

</table>

<br />

<% if current_user && current_user.is_admin? %>
   <%= link_to 'A-New Board', new_admin_board_path %>
<% end %>

app/views/boards/show.html.erb
<p id = "notice"><%= notice %></p>

<p>
<b>Name:</b>
<%= @board.name %>
</p>

<h1>Listing posts -Total<%= @board.posts.size %> posts </h1>
<table>
   <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Content</th>
      <th>Created At</th>
      <th>Updated At</th>
      <th></th>
      <th></th>
      <th></th>
   </tr>
   <% @posts.each do |post| %>
      <tr>
         <td><%= post.id %></td>
         <td><%= post.title %></td>
         <td><%= post.content %></td>
         <td><%= l(post.created_at, :format => :short) %></td>
         <td><%= l(post.updated_at, :format => :short) %></td>
         <td><%= link_to 'Show', board_post_path(@board, post) %></td>
         <% if post.user = current_user %>
            <td><%= link_to 'Edit', edit_board_post_path(@board, post) %></td>
            <td><%= link_to 'Destroy', board_post_path(@board, post), :confirm => 'Are you sure?', :method => :selete %></td>
         <% end %>
      </tr>
   <% end %>
</table>

<%= will_paginate(@posts) %>
<br />

<%= link_to 'Back to boards', boards_path %> | <%= link_to 'New post', new_board_post_path(@board) %>
<% if current_user && current_user.is_admin? %>
   <%= link_to 'A-Edit', edit_admin_board_path(@board) %> |
<% end %>
<%= link_to 'Back', boards_path %>

app/views/common/_user_nav.erb
<div class = "user_navigation">
   <% if user_signed_in? %>
      Hi! <%= current_user.email %>
      <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
      <% if current_user && current_user.is_admin? %>
         <%= link_to 'Admin panel', admin_boards_path %>
      <% end %>
   <% else %>
      <%= link_to 'Sign in', new_user_session_path %>
      <%= link_to 'Sign up', new_user_registration_path %>
   <% end %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

   <h1>Admin panel</h1>
   <p class = "notice"><%= notice %></p>
   <p class = "alert"><%= alert %></p>
   <%= render :partial => 'common/user_nav' %>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

   <p class = "notice"><%= notice %></p>
   <p class = "alert"><%= alert %></p>
   <%= render :partial => 'common/user_nav' %>
<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for @post, :url => board_post_path(@board, @post), :html => {:multipart => true} do |f| %>
   <%= f.label :title, 'Post Title' %>
   <%= f.text_field :title %>
   <%= f.label :content, 'Post Content' %>
   <%= f.text_area :content %>
   <%= f.submit 'Update!' %>
   <div class = "field">
      <%= f.label :upload_image %><br />
      <%= f.file_field :excerpt_image %>
   </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_for @post, :url => board_posts_path(@board), :html => {:multipart => true} do |f| %>
   <%= f.label :title, 'Post Title' %>
   <%= f.text_field :title %>
   <%= f.label :content, 'Post Content' %>
   <%= f.text_area :content %>
   <%= f.submit 'Create!' %>
   <div class = "field">
      <%= f.label :upload_image %><br />
      <%= f.file_field :excerpt_image %>
   </div>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>

<% if @post.excerpt_image %>
   <p>
   <%= image_tag(@post.excerpt_image.url(:medium)) %>
   </p>
<% end %>


<%= link_to 'Back to list', board_posts_path(@board) %> | 
<% if current_user && @post.user_id == current_user.id %>
   <%= link_to 'Edit this post', edit_board_post_path(@board, @post) %>
<% end %>

<% if current_user && current_user.is_admin? %>
   <%= link_to 'A-Edit', edit_admin_board_post_path(@board, @post) %>
<% end %>

<%= link_to 'Back', board_posts_path(@board) %>